CC = gcc
CFLAGS = -std=c99
LDFLAGS = -L.
LDLIBS = -lm

all: wordlengths demo_histogram anagram anaquery

wordlengths: ./Q1/wordlengths.o ./Q1/histogram.o ./Q1/readfile.o
	$(CC) $(CFLAGS) $(LDFLAGS) ./Q1/wordlengths.o ./Q1/histogram.o ./Q1/readfile.o -o wordlengths $(LDLIBS)

demo_histogram: ./Q1/demo_histogram.o ./Q1/histogram.o
	$(CC) $(CFLAGS) $(LDFLAGS) ./Q1/demo_histogram.o ./Q1/histogram.o -o demo_histogram $(LDLIBS)

./Q1/demo_histogram.o: ./Q1/demo_histogram.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q1/demo_histogram.c

./Q1/histogram.o: ./Q1/histogram.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q1/histogram.c

./Q1/wordlengths.o: ./Q1/wordlengths.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q1/wordlengths.c

./Q1/readfile.o: ./Q1/readfile.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q1/readfile.c


anagram: ./Q2/anagram.o ./Q2/anagram_linked_list.o ./Q1/readfile.o ./Q1/histogram.o
	$(CC) $(CFLAGS) $(LDFLAGS) ./Q2/anagram.o ./Q2/anagram_linked_list.o ./Q1/readfile.o ./Q1/histogram.o -o anagram $(LDLIBS)


anaquery: ./Q2/anaquery.o ./Q2/anagram_linked_list.o ./Q1/readfile.o
	$(CC) $(CFLAGS) $(LDFLAGS) ./Q2/anaquery.o ./Q2/anagram_linked_list.o ./Q1/readfile.o -o anaquery

./Q2/anaquery.o: ./Q2/anaquery.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q2/anaquery.c

./Q2/anagram.o: ./Q2/anagram.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q2/anagram.c

./Q2/anagram_linked_list.o: ./Q2/anagram_linked_list.c
	$(CC) $(CFLAGS) $(LDFLAGS) -c ./Q2/anagram_linked_list.c

clean:
	rm -f *.o wordlengths demo_histogram anagram anaquery ./Q1/*.o ./Q2/*.o

